name: storage_inspector
description: A flutter plugin that facilitates inspection and modification of 'local storage' inside a flutter app
version: 0.2.3
homepage: https://github.com/NicolaVerbeeck/flutter_local_storage_inspector

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  async: ^2.8.1
  dart_service_announcement: ^1.2.3
  flutter:
    sdk: flutter
  synchronized: ^3.0.0
  tuple: ^2.0.0
  uri: ^1.0.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
