name: storage_inspector
description: A flutter plugin that facilitates inspection and modification of 'local storage' inside a flutter app
version: 0.4.0
homepage: https://github.com/NicolaVerbeeck/flutter_local_storage_inspector

funding:
  - https://github.com/sponsors/NicolaVerbeeck
  - https://ko-fi.com/nicolaverbeeck

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  async: ^2.11.0
  dart_service_announcement: ^1.2.3
  flutter:
    sdk: flutter
  synchronized: ^3.1.0
  tuple: ^2.0.2
  uri: ^1.0.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
