name: storage_inspector
description: A flutter plugin that facilitates inspection and modification of 'local storage' inside a flutter app
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dart_service_announcement: ^1.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.9
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
